//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyThuVien.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class ChiTietPhieuMuon
    {
        public string Id { get; set; }
        public int MaPhieu { get; set; }
        public string MaTheBanDoc { get; set; }
        public int MaNhanVien { get; set; }
        public Nullable<System.DateTime> NgayMuon { get; set; }
        public Nullable<int> HanTra { get; set; }
    
        public virtual PhieuMuon PhieuMuon { get; set; }
        public virtual NguoiDung NguoiDung { get; set; }
        public virtual DocGia DocGia { get; set; }
    }
}
