
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using QuanLyThuVien.ViewModel;
namespace QuanLyThuVien.Model
{

using System;
    using System.Collections.Generic;

    public partial class ChiTietPhieuMuon : BaseViewModel
    {
        private string _Id;

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ChiTietPhieuMuon()
        {

            this.PhieuMuons = new HashSet<PhieuMuon>();

        }


        public string Id { get => _Id; set { _Id = value;OnPropertyChanged(); } }

        private string _MaTheBanDoc;
        public string MaTheBanDoc { get => _MaTheBanDoc; set { _MaTheBanDoc = value;OnPropertyChanged(); } }

        private int _MaNhanVien;

        private Nullable<System.DateTime> _NgayMuon;

        private Nullable<System.DateTime> _HanTra;

        private string _TrangThai;

        public int MaNhanVien { get => _MaNhanVien; set { _MaNhanVien = value;OnPropertyChanged(); } }
        public DateTime? NgayMuon { get => _NgayMuon; set { _NgayMuon = value;OnPropertyChanged(); } }
        public DateTime? HanTra { get => _HanTra; set { _HanTra = value;OnPropertyChanged(); } }
        public string TrangThai { get => _TrangThai; set { _TrangThai = value;OnPropertyChanged(); } }


        public virtual DocGia DocGia { get; set; }

        public virtual NguoiDung NguoiDung { get; set; }

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

        public virtual ICollection<PhieuMuon> PhieuMuons { get; set; }

    }

}
