
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using QuanLyThuVien.ViewModel;

namespace QuanLyThuVien.Model
{

using System;
    using System.Collections.Generic;
    
public partial class DocGia: BaseViewModel
    {

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public DocGia()
    {

        this.ChiTietPhieuMuons = new HashSet<ChiTietPhieuMuon>();

    }


        private string _Id;

        private string _TenDocGia;

        private string _Email;

        private string _SoDienThoai;

        private string _CMTND;

        private Nullable<System.DateTime> _NgaySinh;

        private Nullable<bool> _GioiTinh;

        private string _NgheNghiep;

        private string _DiaChi;

        private string _AnhDaiDien;

        public string Id { get => _Id; set { _Id = value;OnPropertyChanged(); } }
        public string TenDocGia { get => _TenDocGia; set { _TenDocGia = value; OnPropertyChanged(); } }
        public string Email { get => _Email; set { _Email = value; OnPropertyChanged(); } }
        public string SoDienThoai { get => _SoDienThoai; set { _SoDienThoai = value; OnPropertyChanged(); } }
        public string CMTND { get => _CMTND; set { _CMTND = value; OnPropertyChanged(); } }
        public DateTime? NgaySinh { get => _NgaySinh; set { _NgaySinh = value; OnPropertyChanged(); } }
        public bool? GioiTinh { get => _GioiTinh; set { _GioiTinh = value; OnPropertyChanged(); } }
        public string NgheNghiep { get => _NgheNghiep; set { _NgheNghiep = value; OnPropertyChanged(); } }
        public string DiaChi { get => _DiaChi; set { _DiaChi = value; OnPropertyChanged(); } }
        public string AnhDaiDien { get => _AnhDaiDien; set { _AnhDaiDien = value; OnPropertyChanged(); } }


        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<ChiTietPhieuMuon> ChiTietPhieuMuons { get; set; }

    }

}
