
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using QuanLyThuVien.ViewModel;

namespace QuanLyThuVien.Model
{

using System;
    using System.Collections.Generic;
    
public partial class NhaXuatBan:BaseViewModel
{

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public NhaXuatBan()
    {

        this.TaiLieux = new HashSet<TaiLieu>();

    }


        private int _Id;

        private string _TenNhaXuatBan;

        private string _DiaChi;

        private string _Email;

        private string _SoDienThoai;

        public int Id { get => _Id; set { _Id = value; OnPropertyChanged(); } }
        public string TenNhaXuatBan { get => _TenNhaXuatBan; set { _TenNhaXuatBan = value; OnPropertyChanged(); } }
        public string DiaChi { get => _DiaChi; set { _DiaChi = value; OnPropertyChanged(); } }
        public string Email { get => _Email; set { _Email = value; OnPropertyChanged(); } }
        public string SoDienThoai { get => _SoDienThoai; set { _SoDienThoai = value; OnPropertyChanged(); } }


        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<TaiLieu> TaiLieux { get; set; }

    }

}
