//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using QuanLyThuVien.ViewModel;
namespace QuanLyThuVien.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class NhaXuatBan: BaseViewModel
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public NhaXuatBan()
        {
            this.TaiLieux = new HashSet<TaiLieu>();
        }
    
        public int Id { get; set; }

        private string _TenNhaXuatBan;
        public string TenNhaXuatBan { get=>_TenNhaXuatBan; set { _TenNhaXuatBan = value;OnPropertyChanged(); } }

        private string _DiaChi;
        public string DiaChi { get=>_DiaChi; set { _DiaChi = value;OnPropertyChanged(); }}

        private string _Email;
        public string Email { get=>_Email; set { _Email = value;OnPropertyChanged(); } }

        private string _SoDienThoai;
        public string SoDienThoai { get=>_SoDienThoai; set{ _SoDienThoai = value;OnPropertyChanged(); } }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TaiLieu> TaiLieux { get; set; }
    }
}
