//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using QuanLyThuVien.ViewModel;
namespace QuanLyThuVien.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class QuyenHeThong: BaseViewModel
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public QuyenHeThong()
        {
            this.NguoiDungs = new HashSet<NguoiDung>();
        }
    
        public int Id { get; set; }
        private string _tenQuyen;
        public string TenQuyen { get=>_tenQuyen; set { _tenQuyen = value;OnPropertyChanged(); } }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<NguoiDung> NguoiDungs { get; set; }
    }
}
