//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyThuVien.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class TaiLieu
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TaiLieu()
        {
            this.PhieuMuons = new HashSet<PhieuMuon>();
        }
    
        public string Id { get; set; }
        public int MaTacGia { get; set; }
        public int MaNhaXuatBan { get; set; }
        public int MaTheLoai { get; set; }
        public int MaNgonNgu { get; set; }
        public Nullable<int> SoTrang { get; set; }
        public Nullable<double> GiaBia { get; set; }
        public string ANhBia { get; set; }
        public int MaViTri { get; set; }
        public Nullable<int> SoLuong { get; set; }
    
        public virtual NgonNgu NgonNgu { get; set; }
        public virtual NhaXuatBan NhaXuatBan { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PhieuMuon> PhieuMuons { get; set; }
        public virtual TacGia TacGia { get; set; }
        public virtual TheLoai TheLoai { get; set; }
        public virtual ViTri ViTri { get; set; }
    }
}
