
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using QuanLyThuVien.ViewModel;
namespace QuanLyThuVien.Model
{

using System;
    using System.Collections.Generic;
    
public partial class TaiLieu:BaseViewModel
{

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public TaiLieu()
    {

        this.PhieuMuons = new HashSet<PhieuMuon>();

    }


        private string _Id;

        private string _TuaDe;

        private int _MaTacGia;

        private int _MaNhaXuatBan;

        private int _MaTheLoai;

        private int _MaNgonNgu;

        private Nullable<int> _SoTrang;

        private Nullable<double> _GiaBia;

        private string _AnhBia;

        private int _MaViTri;

        private Nullable<int> _SoLuong;

        public string Id { get => _Id; set { _Id = value;OnPropertyChanged(); } }
        public string TuaDe { get => _TuaDe; set { _TuaDe = value; OnPropertyChanged(); } }
        public int MaTacGia { get => _MaTacGia; set { _MaTacGia = value; OnPropertyChanged(); } }
        public int MaNhaXuatBan { get => _MaNhaXuatBan; set { _MaNhaXuatBan = value; OnPropertyChanged(); } }
        public int MaTheLoai { get => _MaTheLoai; set { _MaTheLoai = value; OnPropertyChanged(); } }
        public int MaNgonNgu { get => _MaNgonNgu; set { _MaNgonNgu = value; OnPropertyChanged(); } }
        public int? SoTrang { get => _SoTrang; set { _SoTrang = value; OnPropertyChanged(); } }
        public double? GiaBia { get => _GiaBia; set { _GiaBia = value; OnPropertyChanged(); } }
        public string AnhBia { get => _AnhBia; set { _AnhBia = value; OnPropertyChanged(); } }
        public int MaViTri { get => _MaViTri; set { _MaViTri = value; OnPropertyChanged(); } }
        public int? SoLuong { get => _SoLuong; set { _SoLuong = value; OnPropertyChanged(); } }


        public virtual NgonNgu NgonNgu { get; set; }

    public virtual NhaXuatBan NhaXuatBan { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<PhieuMuon> PhieuMuons { get; set; }

    public virtual TacGia TacGia { get; set; }

    public virtual TheLoai TheLoai { get; set; }

    public virtual ViTri ViTri { get; set; }
    }

}
