
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using QuanLyThuVien.ViewModel;

namespace QuanLyThuVien.Model
{

using System;
    using System.Collections.Generic;
    
public partial class ViTri:BaseViewModel
{

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public ViTri()
    {

        this.TaiLieux = new HashSet<TaiLieu>();

    }


        private int _Id;

        private Nullable<int> _SoGiaSach;

        private Nullable<int> _SucChua;

        public int Id { get => _Id; set { _Id = value; OnPropertyChanged(); } }
        public int? SoGiaSach { get => _SoGiaSach; set { _SoGiaSach = value; OnPropertyChanged(); } }
        public int? SucChua { get => _SucChua; set { _SucChua = value; OnPropertyChanged(); } }



        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<TaiLieu> TaiLieux { get; set; }
    }

}
